### ISSUE TITLE
Maybe add caveat about issues with multiple mints

### ISSUE THREAD

**Issue by findingsov** [wrapnuts/wrapnuts#1]
When unwrapping:
Error: Got unexpected extra arguments (have balances in 2 mints)

**Comment by wrapnuts** [comment]
a7e6e36

**Comment by wrapnuts** [comment]
Thanks. I've added a warning for now. Will try to replicate this issue and fix it soon

**Comment by wrapnuts** [comment]
@findingsov pls share your logs if error still occurs. I was not able to replicate your error while unwrapping. 

however, i got error while wrapping and being connected to multiple mints. this error has been fixed.
